variable "aws_region" {
  description = "AWS region to deploy into"
  type        = string
  default     = "us-east-1"
}

variable "project_name" {
  description = "Prefix used to name/tag all resources"
  type        = string
  default     = "skillexchange"
}

variable "vpc_cidr" {
  type    = string
  default = "10.20.0.0/16"
}

variable "public_subnet_cidrs" {
  type    = list(string)
  default = ["10.20.1.0/24", "10.20.2.0/24"]
}

variable "private_subnet_cidrs" {
  type    = list(string)
  default = ["10.20.11.0/24", "10.20.12.0/24"]
}

variable "azs" {
  description = "Availability zones to spread subnets across"
  type        = list(string)
  default     = ["us-east-1a", "us-east-1b"]
}

variable "instance_type" {
  type    = string
  default = "t3.micro"
}

variable "db_instance_class" {
  type    = string
  default = "db.t3.micro"
}

variable "db_name" {
  type    = string
  default = "skillexchange"
}

variable "db_username" {
  description = "RDS master username. Not a secret by itself — has a sensible default, override only if you want something else."
  type        = string
  default     = "admin"
}

# No db_password variable - the DB password is generated automatically by
# Terraform (random_password in rds.tf) and never leaves the AWS account.
#
# SSH access exists only via the bastion host now - the app server has no
# public IP and is unreachable directly. The SSH key pair itself is also
# generated by Terraform (tls_private_key in bastion.tf) and stored only
# in AWS Systems Manager Parameter Store (encrypted) - nothing to
# generate, paste, or store as a GitHub secret.
variable "ssh_ingress_cidr" {
  description = "CIDR allowed to SSH into the bastion on port 22. Override via the (non-secret) SSH_INGRESS_CIDR repo variable in GitHub - default is open, which you should tighten to your own IP/32."
  type        = string
  default     = "0.0.0.0/0"
}
